version: '3'
services:
  redis:
    image: redis
    container_name: jeecg-boot-redis
#    ports:
#      - "6379:6379"
#    volumes:
#      - /data
    command: redis-server --appendonly yes
    environment:
      - TZ=Asia/Shanghai
  mysql:
    image: mysql:5.7
    container_name: jeecg-boot-mysql
    ports:
      - "3366:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Shanghai
    volumes:
      - /Users/zhouwenrong/docker/mysql/conf:/etc/mysql
      - /Users/zhouwenrong/docker/mysql/data:/var/lib/mysql
    command: [
      '--lower_case_table_names=1'
    ]
  elasticsearch:
    image: elasticsearch
    container_name: jeecg-boot-elasticsearch
    environment:
      ES_JAVA_OPTS: -Djava.net.preferIPv4Stack=true -Xms1g -Xmx1g
      transport.host: 0.0.0.0
      discovery.type: single-node
      bootstrap.memory_lock: "true"
      discovery.zen.minimum_master_nodes: 1
      discovery.zen.ping.unicast.hosts: elasticsearch
    volumes:
      - /Users/zhouwenrong/docker/elk/elasticsearch/plugins:/usr/share/elasticsearch/plugins #插件文件挂载
      - /Users/zhouwenrong/docker/elk/elasticsearch/data:/usr/share/elasticsearch/data #数据文件挂载
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana:
    image: kibana
    container_name: jeecg-boot-kibana
    links:
      - elasticsearch:elasticsearch
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200 #设置访问elasticsearch的地址
    depends_on:
      - elasticsearch
  logstash:
    image: logstash
    container_name: jeecg-boot-logstash
    command: logstash -f /etc/logstash/conf.d/logstash.conf  #logstash 启动时使用的配置文件
    volumes:
      - /Users/zhouwenrong/docker/elk/logstash/conf.d:/etc/logstash/conf.d #挂载logstash的配置文件
    depends_on:
      - elasticsearch #kibana在elasticsearch启动之后再启动
    links:
      - elasticsearch:elasticsearch #可以用es这个域名访问elasticsearch服务
    ports:
      - 4560:4560
      - 5044:5044
      - 9600:9600

  jeecg-boot:
    image: jeecg-boot
    container_name: jeecg-boot
    volumes:
      - "/Users/zhouwenrong/IdeaProjects/upload/jeecg-boot:/upload"
    environment:
      - "spring.datasource.dynamic.datasource.master.url=jdbc:mysql://mysqldb:3306/jeecg-boot?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false"
      - "spring.datasource.dynamic.datasource.master.username=root"
      - "spring.datasource.dynamic.datasource.master.password=root"
      - "spring.redis.host=redis"
      - "spring.redis.port=6379"
    links:
      - redis:redis
      - mysql:mysqldb
    depends_on:
      - redis
      - mysql
    ports:
      - 8080:8080
    restart: always
  nginx:
#    restart: always
    image: nginx
    container_name: jeecg-boot-ui
    ports:
      - 80:80
    volumes:
      - /Users/zhouwenrong/docker/nginx/conf:/etc/nginx/conf.d
      - /Users/zhouwenrong/docker/nginx/log:/var/log/nginx
      - /Users/zhouwenrong/docker/nginx/www:/var/www
    environment:
      - TZ=Asia/Shanghai
